title: PNU
lang: fa
description: PNU

# ===============================

remote_theme: amkherad/jekyll-rtd-theme # rundocs/jekyll-theme-docsify

author: Ali Mousavi Kherad

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true
    defaults:
      -
        scope:
          path: ""
        values:
          layout: default
      -
        scope:
          path: ""
          type: "docs"
        values:
          seo:
            type: Article
          _comments:
            category: Group navigation links with this field
            order: Used to sort links in the navigation
          _options:
            content:
              width: 800
              height: 2000
      -
        scope:
          path: ""
          type: "posts"
        values:
          _comments:
            type: Marks the impact of this release
    
    # -----------
    # CloudCannon
    
    types:
      - minor
      - major

addons:
  - github
  - i18n
  - plugins
  - analytics

sass:
  style: compressed

copyright:
  revision: true

readme_index:
  with_frontmatter: true

plugins:
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-redirect-from


exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - jekyll-rtd-theme.gemspec

whitelist:
  - jekyll-redirect-from

translate:
  # shortcodes
  danger: خطا
  note: یادداشت
  tip: نکته
  warning: اخطار
  # 404
  not_found: صفحه‌ای پیدا نشد
  # copyright
  revision: بازبینی
  # search
  searching: درحال جستجو
  search: جستجو
  search_docs: جستجو
  search_results: نتایج جستجو
  search_results_found: نتایج جستجو #
  search_results_not_found: هیچ نتیجه‌ای یافت نشد
  